// Salary data informed by BLS OEWS (May 2023), in 2024 US dollars.
// - start: median entry-level salary (age 22-25)
// - mid:   median mid-career salary (age ~42)
// - peak:  median peak-career salary (age ~52)
// - late:  median late-career salary (age ~62)
// - dispersion: typical (p90 - p50) / p50 ratio for the occupation
// Ambition slider picks a percentile from ~p10 to ~p90.

export const CATEGORIES = [
  { id: 'all', label: 'All', emoji: '✨' },
  { id: 'engineering', label: 'Engineering', emoji: '⚙️' },
  { id: 'medicine', label: 'Medicine', emoji: '⚕️' },
  { id: 'business', label: 'Business', emoji: '💼' },
  { id: 'creative', label: 'Creative', emoji: '🎨' },
  { id: 'science', label: 'Science & Edu', emoji: '🔬' },
];

export const CAREERS = [
  {
    id: 'software_engineer',
    category: 'engineering',
    name: 'Software Engineer',
    icon: '💻',
    tagline: 'Build systems, ship products, iterate',
    salary: { start: 85000, mid: 140000, peak: 175000, late: 165000 },
    dispersion: 0.75,
    baseStress: 55, workHours: 45, prestige: 70, jobSecurity: 75, creativity: 70, purpose: 55,
    description: 'High earning potential with strong demand. Balance between analytical and creative work.',
    majors: ['Computer Science', 'Software Engineering', 'Computer Engineering', 'Math', 'Self-taught'],
    blsCode: '15-1252',
  },
  {
    id: 'mechanical_engineer',
    category: 'engineering',
    name: 'Mechanical Engineer',
    icon: '⚙️',
    tagline: 'Design machines, systems, motion',
    salary: { start: 72000, mid: 100000, peak: 125000, late: 120000 },
    dispersion: 0.45,
    baseStress: 55, workHours: 45, prestige: 75, jobSecurity: 80, creativity: 70, purpose: 70,
    description: 'Broadest engineering discipline. Designs everything from engines to robotics to HVAC.',
    majors: ['Mechanical Engineering', 'Aerospace Engineering', 'Physics'],
    blsCode: '17-2141',
  },
  {
    id: 'electrical_engineer',
    category: 'engineering',
    name: 'Electrical Engineer',
    icon: '🔌',
    tagline: 'Circuits, power, signals',
    salary: { start: 78000, mid: 110000, peak: 135000, late: 130000 },
    dispersion: 0.5,
    baseStress: 60, workHours: 46, prestige: 78, jobSecurity: 82, creativity: 65, purpose: 70,
    description: 'Works on electronics, power systems, embedded hardware. Strong demand in semiconductors and EVs.',
    majors: ['Electrical Engineering', 'Computer Engineering', 'Electrical & Computer Eng.', 'Physics'],
    blsCode: '17-2071',
  },
  {
    id: 'civil_engineer',
    category: 'engineering',
    name: 'Civil Engineer',
    icon: '🏗️',
    tagline: 'Build the physical world',
    salary: { start: 68000, mid: 92000, peak: 115000, late: 110000 },
    dispersion: 0.4,
    baseStress: 50, workHours: 44, prestige: 70, jobSecurity: 88, creativity: 55, purpose: 80,
    description: 'Designs bridges, roads, buildings, infrastructure. Very stable with strong public-sector demand.',
    majors: ['Civil Engineering', 'Structural Engineering', 'Environmental Engineering'],
    blsCode: '17-2051',
  },
  {
    id: 'aerospace_engineer',
    category: 'engineering',
    name: 'Aerospace Engineer',
    icon: '✈️',
    tagline: 'Aircraft, rockets, orbital systems',
    salary: { start: 82000, mid: 125000, peak: 155000, late: 148000 },
    dispersion: 0.55,
    baseStress: 65, workHours: 48, prestige: 90, jobSecurity: 75, creativity: 78, purpose: 82,
    description: 'Designs and tests flight vehicles. Thriving with the space economy, cyclical with defense budgets.',
    majors: ['Aerospace Engineering', 'Mechanical Engineering', 'Astronautical Engineering', 'Physics'],
    blsCode: '17-2011',
  },
  {
    id: 'chemical_engineer',
    category: 'engineering',
    name: 'Chemical Engineer',
    icon: '⚗️',
    tagline: 'Reactions, materials, processes',
    salary: { start: 78000, mid: 112000, peak: 140000, late: 132000 },
    dispersion: 0.5,
    baseStress: 62, workHours: 47, prestige: 78, jobSecurity: 78, creativity: 60, purpose: 70,
    description: 'Scales chemistry into industry — pharmaceuticals, energy, materials, food processing.',
    majors: ['Chemical Engineering', 'Chemistry', 'Biomolecular Engineering'],
    blsCode: '17-2041',
  },
  {
    id: 'computer_engineer',
    category: 'engineering',
    name: 'Computer Engineer',
    icon: '🖥️',
    tagline: 'Hardware meets software',
    salary: { start: 80000, mid: 125000, peak: 155000, late: 145000 },
    dispersion: 0.6,
    baseStress: 58, workHours: 46, prestige: 76, jobSecurity: 78, creativity: 68, purpose: 60,
    description: 'Designs processors, embedded systems, firmware. Bridges EE and CS — strong in chips, IoT, and autonomous systems.',
    majors: ['Computer Engineering', 'Electrical Engineering', 'Computer Science'],
    blsCode: '17-2061',
  },
  {
    id: 'biomedical_engineer',
    category: 'engineering',
    name: 'Biomedical Engineer',
    icon: '🧬',
    tagline: 'Engineering meets medicine',
    salary: { start: 72000, mid: 100000, peak: 125000, late: 118000 },
    dispersion: 0.5,
    baseStress: 60, workHours: 46, prestige: 82, jobSecurity: 75, creativity: 80, purpose: 90,
    description: 'Designs medical devices, prosthetics, imaging systems. Fast-growing field with high purpose.',
    majors: ['Biomedical Engineering', 'Mechanical Engineering', 'Electrical Engineering', 'Bioengineering'],
    blsCode: '17-2031',
  },
  {
    id: 'data_scientist',
    category: 'engineering',
    name: 'Data Scientist',
    icon: '📊',
    tagline: 'Models, insights, decisions',
    salary: { start: 92000, mid: 130000, peak: 160000, late: 150000 },
    dispersion: 0.6,
    baseStress: 55, workHours: 44, prestige: 78, jobSecurity: 72, creativity: 72, purpose: 60,
    description: 'Uses statistics and ML to drive decisions. Strong demand across tech, finance, and healthcare.',
    majors: ['Statistics', 'Computer Science', 'Math', 'Data Science', 'Physics', 'Economics'],
    blsCode: '15-2051',
  },
  {
    id: 'doctor',
    category: 'medicine',
    name: 'Doctor',
    icon: '⚕️',
    tagline: 'Heal, diagnose, dedicate',
    salary: { start: 65000, mid: 245000, peak: 310000, late: 285000 },
    dispersion: 0.6,
    baseStress: 80, workHours: 60, prestige: 95, jobSecurity: 95, creativity: 40, purpose: 95,
    description: 'High purpose and prestige, but years of training and sustained high stress.',
    majors: ['Biology (pre-med)', 'Biochemistry', 'Neuroscience', 'Chemistry', 'Health Sciences'],
    delayedStart: 8,
    trainingWage: 62000,
    trainingDebt: 200000,
    blsCode: '29-1210',
  },
  {
    id: 'nurse',
    category: 'medicine',
    name: 'Nurse',
    icon: '🩺',
    tagline: 'Care, support, steady',
    salary: { start: 68000, mid: 88000, peak: 102000, late: 98000 },
    dispersion: 0.35,
    baseStress: 70, workHours: 48, prestige: 70, jobSecurity: 95, creativity: 30, purpose: 92,
    description: 'Very high job security and purpose. Physically demanding with emotional weight.',
    majors: ['Nursing (BSN)', 'Health Sciences', 'Biology'],
    blsCode: '29-1141',
  },
  {
    id: 'lawyer',
    category: 'business',
    name: 'Lawyer',
    icon: '⚖️',
    tagline: 'Argue, draft, advocate',
    salary: { start: 80000, mid: 140000, peak: 195000, late: 185000 },
    dispersion: 0.9,
    baseStress: 78, workHours: 58, prestige: 85, jobSecurity: 75, creativity: 55, purpose: 60,
    description: 'Prestigious and lucrative, but billable hours are relentless. Huge dispersion (BigLaw vs solo).',
    majors: ['Political Science', 'English', 'History', 'Philosophy', 'Pre-law (+ JD)'],
    delayedStart: 3,
    trainingWage: 0,
    trainingDebt: 150000,
    blsCode: '23-1011',
  },
  {
    id: 'finance',
    category: 'business',
    name: 'Finance Analyst',
    icon: '💼',
    tagline: 'Model, invest, optimize',
    salary: { start: 78000, mid: 135000, peak: 205000, late: 195000 },
    dispersion: 1.1,
    baseStress: 75, workHours: 55, prestige: 80, jobSecurity: 65, creativity: 35, purpose: 40,
    description: 'Strong earning trajectory with bonuses, but long hours and market-tied volatility.',
    majors: ['Finance', 'Economics', 'Accounting', 'Math', 'Business Administration'],
    blsCode: '13-2051',
  },
  {
    id: 'entrepreneur',
    category: 'business',
    name: 'Entrepreneur',
    icon: '🚀',
    tagline: 'Build, risk, scale',
    salary: { start: 35000, mid: 85000, peak: 160000, late: 140000 },
    dispersion: 1.8,
    baseStress: 85, workHours: 65, prestige: 75, jobSecurity: 25, creativity: 85, purpose: 85,
    description: 'Massive upside and autonomy, but extreme volatility and stress. High failure rate.',
    majors: ['Business', 'Any field + hustle', 'CS', 'Economics', 'No degree'],
  },
  {
    id: 'teacher',
    category: 'science',
    name: 'Teacher',
    icon: '📚',
    tagline: 'Educate, mentor, inspire',
    salary: { start: 46000, mid: 62000, peak: 78000, late: 76000 },
    dispersion: 0.35,
    baseStress: 50, workHours: 42, prestige: 60, jobSecurity: 85, creativity: 65, purpose: 90,
    description: 'High purpose, stable, summers off. Lower ceiling but meaningful impact.',
    majors: ['Education', 'English', 'Math', 'History', 'Subject area + teaching cert'],
    blsCode: '25-2021',
  },
  {
    id: 'researcher',
    category: 'science',
    name: 'Scientist',
    icon: '🔬',
    tagline: 'Investigate, publish, discover',
    salary: { start: 58000, mid: 95000, peak: 125000, late: 118000 },
    dispersion: 0.5,
    baseStress: 55, workHours: 48, prestige: 85, jobSecurity: 60, creativity: 80, purpose: 90,
    description: 'Intellectual depth and purpose. Slow salary growth but deeply fulfilling.',
    majors: ['Physics', 'Biology', 'Chemistry', 'Neuroscience', 'PhD required'],
    delayedStart: 6,
    trainingWage: 36000,
    blsCode: '19-1020',
  },
  {
    id: 'artist',
    category: 'creative',
    name: 'Artist',
    icon: '🎨',
    tagline: 'Create, express, freelance',
    salary: { start: 34000, mid: 52000, peak: 66000, late: 62000 },
    dispersion: 1.2,
    baseStress: 45, workHours: 38, prestige: 50, jobSecurity: 35, creativity: 98, purpose: 80,
    description: 'Creative freedom and flexibility, but volatile income and lower financial ceiling.',
    majors: ['Fine Arts', 'Graphic Design', 'Illustration', 'Film', 'No degree required'],
    blsCode: '27-1013',
  },
  {
    id: 'influencer',
    category: 'creative',
    name: 'Content Creator',
    icon: '📱',
    tagline: 'Post, engage, monetize',
    salary: { start: 28000, mid: 70000, peak: 130000, late: 90000 },
    dispersion: 2.0,
    baseStress: 60, workHours: 35, prestige: 55, jobSecurity: 20, creativity: 90, purpose: 55,
    description: 'Huge upside if you hit, flexibility always — but fame is fickle and attention is exhausting.',
    majors: ['Marketing', 'Communications', 'Film', 'Any field', 'No degree required'],
  },
  {
    id: 'pharmacist',
    category: 'medicine',
    name: 'Pharmacist',
    icon: '💊',
    tagline: 'Dispense, counsel, compound',
    salary: { start: 120000, mid: 135000, peak: 145000, late: 140000 },
    dispersion: 0.25,
    baseStress: 55, workHours: 42, prestige: 78, jobSecurity: 85, creativity: 25, purpose: 80,
    description: 'High starting salary with stable hours, but a flat growth curve. PharmD required (4 years post-BS).',
    majors: ['Chemistry', 'Biology', 'Public Health'],
    delayedStart: 4, trainingWage: 0, trainingDebt: 170000, blsCode: '29-1051',
  },
  {
    id: 'dentist',
    category: 'medicine',
    name: 'Dentist',
    icon: '🦷',
    tagline: 'Restore, prevent, operate',
    salary: { start: 130000, mid: 180000, peak: 220000, late: 200000 },
    dispersion: 0.5,
    baseStress: 60, workHours: 38, prestige: 82, jobSecurity: 90, creativity: 40, purpose: 75,
    description: 'Great work-life balance for a medical profession. Own your practice for max upside. DDS/DMD required.',
    majors: ['Biology', 'Chemistry', 'Neuroscience'],
    delayedStart: 4, trainingWage: 0, trainingDebt: 250000, blsCode: '29-1020',
  },
  {
    id: 'physician_assistant',
    category: 'medicine',
    name: 'Physician Assistant',
    icon: '🩻',
    tagline: 'Diagnose, treat, assist',
    salary: { start: 100000, mid: 120000, peak: 135000, late: 130000 },
    dispersion: 0.25,
    baseStress: 65, workHours: 42, prestige: 75, jobSecurity: 95, creativity: 35, purpose: 90,
    description: 'Fastest-growing medical career. Less training than MD, similar day-to-day impact.',
    majors: ['Biology', 'Nursing (BSN)', 'Public Health'],
    delayedStart: 3, trainingWage: 0, trainingDebt: 100000, blsCode: '29-1071',
  },
  {
    id: 'psychologist',
    category: 'science',
    name: 'Psychologist',
    icon: '🧠',
    tagline: 'Assess, treat, research',
    salary: { start: 55000, mid: 85000, peak: 110000, late: 105000 },
    dispersion: 0.5,
    baseStress: 50, workHours: 40, prestige: 75, jobSecurity: 78, creativity: 65, purpose: 88,
    description: 'Clinical or research track. PsyD/PhD required for clinical — long training, deep reward.',
    majors: ['Psychology', 'Neuroscience', 'Biology'],
    delayedStart: 5, trainingWage: 28000, blsCode: '19-3031',
  },
  {
    id: 'architect',
    category: 'creative',
    name: 'Architect',
    icon: '🏛️',
    tagline: 'Design, draft, build',
    salary: { start: 52000, mid: 82000, peak: 105000, late: 100000 },
    dispersion: 0.5,
    baseStress: 60, workHours: 45, prestige: 80, jobSecurity: 65, creativity: 95, purpose: 75,
    description: 'Creative + technical. Long licensure path (5-yr B.Arch + internship) but deeply satisfying.',
    majors: ['Architecture', 'Fine Arts / Design', 'Civil Engineering'],
    delayedStart: 1, trainingWage: 48000, blsCode: '17-1011',
  },
  {
    id: 'management_consultant',
    category: 'business',
    name: 'Management Consultant',
    icon: '📋',
    tagline: 'Advise, optimize, present',
    salary: { start: 95000, mid: 160000, peak: 240000, late: 220000 },
    dispersion: 0.8,
    baseStress: 80, workHours: 60, prestige: 85, jobSecurity: 60, creativity: 55, purpose: 45,
    description: 'High-pay, high-travel, high-stress. MBB (McKinsey, Bain, BCG) or bust for top trajectory.',
    majors: ['Economics', 'Finance / Business', 'Math', 'Engineering (any)'],
    blsCode: '13-1111',
  },
  {
    id: 'accountant',
    category: 'business',
    name: 'Accountant',
    icon: '📒',
    tagline: 'Audit, tax, report',
    salary: { start: 58000, mid: 82000, peak: 105000, late: 100000 },
    dispersion: 0.45,
    baseStress: 55, workHours: 45, prestige: 62, jobSecurity: 88, creativity: 20, purpose: 45,
    description: 'Extremely stable, always in demand. CPA license required for advancement. Tax season is brutal.',
    majors: ['Accounting', 'Finance / Business', 'Economics'],
    blsCode: '13-2011',
  },
  {
    id: 'marketing_manager',
    category: 'business',
    name: 'Marketing Manager',
    icon: '📣',
    tagline: 'Brand, strategy, growth',
    salary: { start: 58000, mid: 95000, peak: 140000, late: 130000 },
    dispersion: 0.6,
    baseStress: 60, workHours: 46, prestige: 68, jobSecurity: 65, creativity: 75, purpose: 45,
    description: 'Creative + analytical. Digital marketing has exploded career options and remote flexibility.',
    majors: ['Marketing', 'Communications', 'Fine Arts / Design', 'Business'],
    blsCode: '11-2021',
  },
  {
    id: 'product_manager',
    category: 'business',
    name: 'Product Manager',
    icon: '🎯',
    tagline: 'Ship, prioritize, align',
    salary: { start: 90000, mid: 140000, peak: 185000, late: 170000 },
    dispersion: 0.65,
    baseStress: 70, workHours: 50, prestige: 75, jobSecurity: 68, creativity: 72, purpose: 60,
    description: 'The "CEO of the product." Cross-functional leadership role, huge in tech.',
    majors: ['Computer Science', 'Finance / Business', 'Economics', 'Any field'],
    blsCode: '15-1299',
  },
  {
    id: 'cybersecurity_analyst',
    category: 'engineering',
    name: 'Cybersecurity Analyst',
    icon: '🔒',
    tagline: 'Defend, detect, respond',
    salary: { start: 82000, mid: 115000, peak: 145000, late: 138000 },
    dispersion: 0.5,
    baseStress: 65, workHours: 44, prestige: 72, jobSecurity: 90, creativity: 55, purpose: 72,
    description: 'Massive demand, critical role. Mix of technical depth and investigative thinking.',
    majors: ['Cybersecurity', 'Computer Science', 'Computer Engineering'],
    blsCode: '15-1212',
  },
  {
    id: 'environmental_engineer',
    category: 'engineering',
    name: 'Environmental Engineer',
    icon: '🌱',
    tagline: 'Clean, sustain, remediate',
    salary: { start: 65000, mid: 92000, peak: 115000, late: 110000 },
    dispersion: 0.4,
    baseStress: 50, workHours: 43, prestige: 72, jobSecurity: 82, creativity: 60, purpose: 92,
    description: 'Water, air, soil — cleaning up and building sustainably. Growing fast with climate focus.',
    majors: ['Environmental Engineering', 'Civil Engineering', 'Chemical Engineering'],
    blsCode: '17-2081',
  },
  {
    id: 'ux_designer',
    category: 'creative',
    name: 'UX Designer',
    icon: '✏️',
    tagline: 'Research, wireframe, test',
    salary: { start: 72000, mid: 110000, peak: 140000, late: 130000 },
    dispersion: 0.5,
    baseStress: 50, workHours: 42, prestige: 68, jobSecurity: 72, creativity: 90, purpose: 65,
    description: 'Design how people interact with products. High demand in tech, strong remote culture.',
    majors: ['Fine Arts / Design', 'Psychology', 'Computer Science', 'Communications'],
    blsCode: '15-1255',
  },
];

// Life events impact in real (today's) dollars.
export const LIFE_EVENTS = [
  { year: 5, title: 'First big promotion', impact: { salary: 1.15, happiness: 8 }, chance: 0.7 },
  { year: 8, title: 'Buy a home (down payment)', impact: { netWorth: -60000, happiness: 10, stress: 5 }, chance: 0.5 },
  { year: 10, title: 'Career pivot opportunity', impact: { salary: 1.1, stress: 10 }, chance: 0.4 },
  { year: 12, title: 'Burnout episode', impact: { stress: 20, happiness: -15 }, chance: 0.3, negative: true },
  { year: 15, title: 'Industry boom', impact: { salary: 1.2, happiness: 5 }, chance: 0.4 },
  { year: 18, title: 'Market downturn', impact: { salary: 0.88, stress: 10, netWorth: -30000 }, chance: 0.3, negative: true },
  { year: 22, title: 'Senior leadership role', impact: { salary: 1.25, prestige: 10 }, chance: 0.5 },
  { year: 25, title: 'Sabbatical year', impact: { happiness: 20, stress: -25, salary: 0.5 }, chance: 0.25 },
];
